services:
  api:
    build:
      context: ..
      dockerfile: cmd/api/Dockerfile
    env_file: base.env
    ports:
      - "8001"
    depends_on:
      - postgres
      - redis
    networks:
      - app_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  scheduler:
    build:
      context: ..
      dockerfile: cmd/scheduler/Dockerfile
    env_file: base.env
    depends_on:
      - postgres
      - redis
    networks:
      - app_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  worker:
    build:
      context: ..
      dockerfile: cmd/worker/Dockerfile
    env_file: base.env
    depends_on:
      - postgres
      - redis
    networks:
      - app_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "url-shortener-db"
      POSTGRES_USER: "url-shortener-db-user"
      POSTGRES_PASSWORD: "url-shortener-db-pass"
    ports:
      - "5432"
    networks:
      - app_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  pgbouncer:
    image: edoburu/pgbouncer
    ports:
      - "6432"
    volumes:
      - ./pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./userlist.txt:/etc/pgbouncer/userlist.txt
    depends_on:
      - postgres
    networks:
      - app_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  redis:
    image: redis:latest
    ports:
      - "6379"
    networks:
      - app_network
    volumes:
      - redis_data:/data
    command: ["redis-server", "--notify-keyspace-events", "Ex"]
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  migrate:
    image: arigaio/atlas:latest
    command: >
      migrate apply
      --url postgres://url-shortener-db-user:url-shortener-db-pass@postgres:5432/url-shortener-db?sslmode=disable
    depends_on:
      - postgres
    networks:
      - app_network
    volumes:
      - ./migrations/:/migrations

  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - scheduler
      - worker
    networks:
      - app_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: