services:
  shortener-app:
    container_name: url-shortener-app
    build:
      context: ..
      dockerfile: cmd/http_server/Dockerfile
    env_file: base.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - app_network

  shortener-scheduler:
    container_name: url-shortener-scheduler
    build:
      context: ..
      dockerfile: cmd/async_server/Dockerfile
    env_file: base.env
    depends_on:
      - postgres
      - redis
    networks:
      - app_network

  postgres:
    container_name: url-shortener-postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "url-shortener-db"
      POSTGRES_USER: "url-shortener-db-user"
      POSTGRES_PASSWORD: "url-shortener-db-pass"
    ports:
      - "5432:5432"
    networks:
      - app_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d

  pgbouncer:
    container_name: url-shortener-pgbouncer
    image: edoburu/pgbouncer
    ports:
      - "6432:6432"
    volumes:
      - ./pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./userlist.txt:/etc/pgbouncer/userlist.txt
    depends_on:
      - postgres
    networks:
      - app_network

  redis:
    container_name: url-shortener-redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app_network
    volumes:
      - redis_data:/data
    command: ["redis-server", "--notify-keyspace-events", "Ex"]

  migrate:
    image: arigaio/atlas:latest
    command: >
      migrate apply
      --url postgres://url-shortener-db-user:url-shortener-db-pass@postgres:5432/url-shortener-db?sslmode=disable
    depends_on:
      - postgres
    networks:
      - app_network
    volumes:
      - ./migrations/:/migrations

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: