version: "2"
linters:
  default: standard
  enable:
    - staticcheck
    - govet
    - gosec
    - errcheck
    
formatters:
  enable:
    - gofmt
    - goimports
    - gci
    - golines
    - swaggo
    - gofumpt