version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: url-shortener-db
      POSTGRES_USER: url-shortener-db-user
      POSTGRES_PASSWORD: url-shortener-db-pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./deploy/postgres/init-scripts:/docker-entrypoint-initdb.d

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    command: ["redis-server", "--notify-keyspace-events", "Ex"]

  migrate:
    image: arigaio/atlas:latest
    command: >
      migrate apply
      --url postgres://url-shortener-db-user:url-shortener-db-pass@postgres:5432/url-shortener-db?sslmode=disable
    depends_on:
      - postgres
    volumes:
      - ./migrations/:/migrations
    profiles: ["migrate"]

volumes:
  postgres_dev_data:
  redis_dev_data:
