version: '3.9'
services:
#  app:
#    container_name: url-shortener-app
#    build:
#      context: ..
#      dockerfile: Dockerfile
#    env_file: base.env
#    depends_on:
#      - postgres
#      - redis
#    networks:
#      - app_network

  postgres:
    container_name: url-shortener-postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "url-shortener-db"
      POSTGRES_USER: "url-shortener-db-user"
      POSTGRES_PASSWORD: "url-shortener-db-pass"
    ports:
      - "5432:5432"
    networks:
      - app_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: url-shortener-redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app_network
    volumes:
      - redis_data:/data

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: