// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: click_counts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const incrementClickCount = `-- name: IncrementClickCount :exec
UPDATE click_counts
SET total_clicks = total_clicks + $1
WHERE url_id = $2
`

type IncrementClickCountParams struct {
	TotalClicks int64
	UrlID       uuid.UUID
}

// Increment click count
func (q *Queries) IncrementClickCount(ctx context.Context, arg IncrementClickCountParams) error {
	_, err := q.db.Exec(ctx, incrementClickCount, arg.TotalClicks, arg.UrlID)
	return err
}

const insertClickCount = `-- name: InsertClickCount :exec
INSERT INTO click_counts (url_id)
VALUES ($1)
`

// Create click count record
func (q *Queries) InsertClickCount(ctx context.Context, urlID uuid.UUID) error {
	_, err := q.db.Exec(ctx, insertClickCount, urlID)
	return err
}
