// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ClickCount struct {
	UrlID       uuid.UUID
	TotalClicks int64
}

type Url struct {
	ID            uuid.UUID
	OriginalUrl   string
	ShortenedCode string
	UserID        pgtype.UUID
	IpAddress     *string
	IsDeleted     *bool
	IsActive      *bool
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
	DeletedAt     pgtype.Timestamp
}

type User struct {
	ID        uuid.UUID
	Username  string
	Password  string
	IsDeleted *bool
	IsActive  *bool
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}
