// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type ClickCount struct {
	UrlID       uuid.UUID
	TotalClicks int64
}

type Url struct {
	ID            uuid.UUID
	OriginalUrl   string
	ShortenedCode string
	UserID        *uuid.UUID
	IpAddress     *string
	IsDeleted     *bool
	IsActive      *bool
	CreatedAt     time.Time
	UpdatedAt     *time.Time
	DeletedAt     *time.Time
}

type User struct {
	ID        uuid.UUID
	Username  string
	Password  string
	IsDeleted *bool
	IsActive  *bool
	CreatedAt time.Time
	UpdatedAt *time.Time
	DeletedAt *time.Time
}
