// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Url struct {
	ID            int32
	OriginalUrl   string
	ShortenedCode string
	UserID        int32
	CreatedAt     pgtype.Timestamptz
}

type User struct {
	ID        int32
	Username  string
	CreatedAt pgtype.Timestamptz
}
