// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Create a new shortened URL for a specific user
	CreateURL(ctx context.Context, arg CreateURLParams) (CreateURLRow, error)
	// Insert a new user
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Delete expired url by short code
	DeleteExpiredUrlByShortCode(ctx context.Context, arg DeleteExpiredUrlByShortCodeParams) error
	// Get url ID by short code
	GetIDByShortCode(ctx context.Context, shortenedCode string) (uuid.UUID, error)
	// Get the original URL by shortened code
	GetURLByCode(ctx context.Context, shortenedCode string) (string, error)
	// Get the original URL by url ID
	GetURLByID(ctx context.Context, id uuid.UUID) (string, error)
	// Get Urls by User ID or IpAddr
	GetUrlsByUser(ctx context.Context, arg GetUrlsByUserParams) ([]GetUrlsByUserRow, error)
	// Get user by user id
	GetUserByUserID(ctx context.Context, id uuid.UUID) (User, error)
	// Get user by username
	GetUserByUsername(ctx context.Context, username string) (User, error)
	// Increment click count
	IncrementClickCount(ctx context.Context, arg IncrementClickCountParams) error
	// Create click count record
	InsertClickCount(ctx context.Context, urlID uuid.UUID) error
	// Check username already taken
	UserExists(ctx context.Context, username string) (bool, error)
}

var _ Querier = (*Queries)(nil)
