// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: url.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createURL = `-- name: CreateURL :one
INSERT INTO urls (original_url, shortened_code, user_id)
VALUES ($1, $2, $3)
RETURNING id, original_url, shortened_code, user_id
`

type CreateURLParams struct {
	OriginalUrl   string
	ShortenedCode string
	UserID        *uuid.UUID
}

type CreateURLRow struct {
	ID            uuid.UUID
	OriginalUrl   string
	ShortenedCode string
	UserID        *uuid.UUID
}

// Create a new shortened URL for a specific user
func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (CreateURLRow, error) {
	row := q.db.QueryRow(ctx, createURL, arg.OriginalUrl, arg.ShortenedCode, arg.UserID)
	var i CreateURLRow
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortenedCode,
		&i.UserID,
	)
	return i, err
}

const deleteExpiredUrlByShortCode = `-- name: DeleteExpiredUrlByShortCode :exec
UPDATE urls
SET is_deleted = true, is_active = false, deleted_at = $1
WHERE shortened_code = $2
`

type DeleteExpiredUrlByShortCodeParams struct {
	DeletedAt     *time.Time
	ShortenedCode string
}

// Delete expired url by short code
func (q *Queries) DeleteExpiredUrlByShortCode(ctx context.Context, arg DeleteExpiredUrlByShortCodeParams) error {
	_, err := q.db.Exec(ctx, deleteExpiredUrlByShortCode, arg.DeletedAt, arg.ShortenedCode)
	return err
}

const getIDByShortCode = `-- name: GetIDByShortCode :one
SELECT id
FROM urls
where shortened_code = $1
`

// Get url ID by short code
func (q *Queries) GetIDByShortCode(ctx context.Context, shortenedCode string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getIDByShortCode, shortenedCode)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getURLByCode = `-- name: GetURLByCode :one
SELECT original_url
FROM urls
WHERE shortened_code = $1 and is_active = True and is_deleted = False
`

// Get the original URL by shortened code
func (q *Queries) GetURLByCode(ctx context.Context, shortenedCode string) (string, error) {
	row := q.db.QueryRow(ctx, getURLByCode, shortenedCode)
	var original_url string
	err := row.Scan(&original_url)
	return original_url, err
}
